X6739: power: Uprev powerhal extension's android.hardware.power-V4 dependency to android.hardware.power-V5-ndk
* Needed on A15 QPR1, or else build fails with this error

error: hardware/lineage/interfaces/power-libperfmgr/Android.bp:14:1: module "android.hardware.power-service.lineage-libperfmgr" variant "
android_vendor_arm64_armv8-2a-dotprod": depends on multiple versions of the same aidl_interface: android.hardware.power-V4-ndk-source, android.hardware.power-V5-ndk-source
error hardware/lineage/interfaces/power-libperfmgr/Android.bp:14:1: module "android.hardware.power-service.lineage-libperfmgr" variant
android_vendor_arm64_armv8-2a-dotprod": Dependency path:
via tag cc.libraryDependencyTag: { Kind:staticLibrary Dependency Order: normalLibrary Dependency wholeStatic: true reexportFlags:t rue explicitlyVersioned: false dataLib:false ndk:false staticUnwinder:false makeSuffix: skipApexAllowedDependenciesCheck:false excludeInApex:false excludeInNonApex: false unexportedSymbols:false}
libperfmgr-ext-transsion{os:android,image:vendor, arch: arm64_armv8-2a-dotprod, link:static}
tag cc.library Dependency Tag: { Kind:sharedLibrary Dependency Order: normal Library Dependency wholeStatic: false reexportFlags:
via false explicitlyVersioned: false datalib:false ndk: false staticUnwinder:false makeSuffix: skipApexAllowed Dependencies Check:false excludeInApex:false excludeInNonApex: false unexportedSymbols:false}

Signed-off-by: Shirayuki39 <lorddemecrius83@proton.me>